export const invoice = {
  id: "5df3180a09ea16dc4b95f910",
  invoice_no: "201906-28",
  balance: "$2,283.74",
  company: "THT-SPACE",
  email: "tht-space@gmail.com",
  phone: "+880 176 0053135",
  address: "MSSFB # 4, UTTRA EPZ, NILPHAMRI, RANGPUR, BANGLADESH",
  trans_date: "2023-06-12",
  due_date: "2023-06-13",
  items: [
    {
      sno: 1,
      desc: "ad sunt culpa occaecat qui",
      qty: 5,
      rate: 405.89,
    },
    {
      sno: 2,
      desc: "cillum quis sunt qui aute",
      qty: 5,
      rate: 373.11,
    },
    {
      sno: 3,
      desc: "ea commodo labore culpa irure",
      qty: 5,
      rate: 458.61,
    },
    {
      sno: 4,
      desc: "nisi consequat et adipisicing dolor",
      qty: 10,
      rate: 725.24,
    },
    {
      sno: 5,
      desc: "proident cillum anim elit esse",
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 6,
      desc: "proident cillum anim elit esse",
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 7,
      desc: "proident cillum anim elit esse",
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 8,
      desc: "proident cillum anim elit esse",
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 9,
      desc: "proident cillum anim elit esse",
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 10,
      desc: "proident cillum anim elit esse",
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 11,
      desc: "proident cillum anim elit esse",
      qty: 4,
      rate: 141.02,
    },
    {
      sno: 12,
      desc: "proident cillum anim elit esse",
      qty: 6,
      rate: 150.02,
    },
    {
      sno: 13,
      desc: "Test last",
      qty: 5,
      rate: 250.02,
    },
  ],
};
